### ISSUE TITLE
Update fabricademy banner

### ISSUE THREAD

**Issue by fibasile** [fabfoundation/fabfoundation#14]

**Comment by fibasile** [comment]
Check with the fabricademy team for the updated picture we have a new one for 2019

**Comment by rebeccaottinger** [comment]
Ok I will check!

**Comment by rebeccaottinger** [comment]
@fibasile Anastasia gave me access to the folder with the new pictures... 
https://drive.google.com/drive/folders/1pM0oCsqqvU4rQ0AtWU5wD3l2ZeRFdzC7

[FB-BANNER.pdf](https://github.com/fablabbcn/fabfoundation/files/3039677/FB-BANNER.pdf)

**Comment by fibasile** [comment]
https://user-images.githubusercontent.com/40209195/55638198-ef36d500-57c6-11e9-9afc-52b545b3ff82.jpg

**Comment by rebeccaottinger** [comment]
@fibasile Where exactly on the website were you referencing there is a bug/ new banner needs to be uploaded? Thanks!

**Comment by JMMolenaar** [comment]
No longer relevant
