### ISSUE TITLE
Add Luciano's fab lab brochure to the about page 

### ISSUE THREAD

**Issue by rebeccaottinger** [fabfoundation/fabfoundation#18]
Add as a button in the ".com" section that allows you to download the pdf. If Luciano doesn't provide the brochure as pdf before next week Rebecca will!

**Comment by fibasile** [comment]
Where is this pdf?

**Comment by rebeccaottinger** [comment]
@fibasile  did you get the brochure?

**Comment by fibasile** [comment]
No but I added the button in the data file, just upload it an add the link there
