### ISSUE TITLE
News section- add an easy way for the network to submit news

### ISSUE THREAD

**Issue by rebeccaottinger** [fabfoundation/fabfoundation#23]
Some kind of link where people fill out a form that creates a news story for us to approve, with name, title, text, and photo, and have a space for this news in the news section of the website, maybe they are uploaded to Fab News section (currently press releases section) once they're approved?

**Comment by fibasile** [comment]
I prepared this:
https://forms.fabfoundation.org/press/add

The form sends the data by email (to me, need to add other email addresses) but also stores it in a database. We can find a way to import the data in the website or simply copy and paste.

There's a web panel to access the data (Ask me for the password). 
https://forms.fabfoundation.org/admin

**Comment by rebeccaottinger** [comment]
@fibasile  This is great!! I think we can also add my e-mail address to receive the forms. 

Can you add an option to attach a photo?

What would you suggest for importing the data? Is there a way to set it up so that if we 'approve' the submission, it automatically gets uploaded to the news section of the website in a certain place with all the info? Worse comes to worse can copy and paste.

Thank you!

**Comment by fibasile** [comment]
The image and attachment are now online.

Yes the approved can be automatically fed into the website.

This would follow having the website pulling data from this system and all existing data imported.

So we can keep this on pause until there is more time I guess.

**Comment by rebeccaottinger** [comment]
Sounds good. For now, I could put the link to the form on the website so people can submit. Would you and I both get a notification every time someone submits something?

**Comment by fibasile** [comment]
Tested both forms and I think we are good to go, you should have received few emails from it@fabacademy.org.

Make a test yourself for both forms and you can add the links to the website. 

*I deleted all the test submissions up to now*

**Comment by rebeccaottinger** [comment]
I did, it's great.

Any way to change "kind" to "type of publication" and underneath have it
say "Select the type of publication". I can change it but wasn't sure where
to find the form in Github.

Where do the forms live? Is it in the website's repository on github? Just
good to know!


Thanks, Fiore!

Rebecca Ottinger
Executive Assistant to President & CEO
The Fab Foundation
50 Milk St., 16th Floor
<https://maps.google.com/?q=50+Milk+St.,+16th+Floor+Boston,+MA+02109&entry=gmail&source=g>
Boston, MA 02109
<https://maps.google.com/?q=50+Milk+St.,+16th+Floor+Boston,+MA+02109&entry=gmail&source=g>
+1 (617) 412 - 6295
Rebecca@fabfoundation.org
http://www.fabfoundation.org/

<http://goog_1217452108>
[image: https://www.scopesdf.org/] <https://www.scopesdf.org/>

**Comment by fibasile** [comment]
They are on a separate machine as github can't host databases. I can change
the labels.

Il Gio 18 Apr 2019, 20:23 rebeccaottinger <notifications@github.com> ha
scritto:

**Comment by rebeccaottinger** [comment]
Great! Thank you!

Rebecca Ottinger
Executive Assistant to President & CEO
The Fab Foundation
50 Milk St., 16th Floor
<https://maps.google.com/?q=50+Milk+St.,+16th+Floor+Boston,+MA+02109&entry=gmail&source=g>
Boston, MA 02109
<https://maps.google.com/?q=50+Milk+St.,+16th+Floor+Boston,+MA+02109&entry=gmail&source=g>
+1 (617) 412 - 6295
Rebecca@fabfoundation.org
http://www.fabfoundation.org/

<http://goog_1217452108>
[image: https://www.scopesdf.org/] <https://www.scopesdf.org/>
