### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by rebeccaottinger** [fabfoundation/fabfoundation#26]
1. Home page- Learn more about the fab foundation button in the blue box leads to an error

2. fab foundation forum: 'contact' button leads to an error (should lead to forum e-mail)

3. global initiatives- on my computer, the fab economy website is showing up as 'not secure' and I can't view it even when I click view anyways... is there a different link? is this the new one you were showing us all on one of our Monday calls? i know you said that was a work in progress, but it looked great!

4. Thank you for working on the look of the top of the home page!! Don't know how I feel about the red outline though now that we see it... what do you think? I'm wondering what it would look like if it was around the two smaller news highlight boxes instead of the bigger outline box...

**Comment by fibasile** [comment]
![image](https://user-images.githubusercontent.com/32947/57124467-3a241800-6d86-11e9-9b95-8e7406e6acc4.png)

**Comment by fibasile** [comment]
1. fixed
2. fixed
3. fixed to the right link
4. I'm restoring the look without red lines (don't work for me), see above for an example
