### ISSUE TITLE
April newsletter linking to fab census

### ISSUE THREAD

**Issue by rebeccaottinger** [fabfoundation/fabfoundation#29]
Can't figure out why, but when you click on the April newsletter (on the home page and in the news section) it leads to the fab census news blast, not the April newsletter text. But in github when i search for the April newsletter, the correct text is there. 

Any thoughts?

**Comment by fibasile** [comment]
It's the permalink: /april-newsletter

This field basically defines the address where each posts appears.

I changed it to fab-census
