### ISSUE TITLE
Remove extra box from Fab Lab Network page

### ISSUE THREAD

**Issue by fibasile** [fabfoundation/fabfoundation#4]
- FFF- there is a “projects and initiatives” box at the bottom that won’t go away and is not in the html file
- add FFF e-mail in the description

**Comment by fibasile** [comment]
Can't find this, can you post a screenshot?

**Comment by rebeccaottinger** [comment]
<img width="1107" alt="Screen Shot 2019-03-13 at 9 27 49 AM" src="https://user-images.githubusercontent.com/48486398/54282502-84510000-4572-11e9-851b-f1b2b1ba064a.png">

It's just the "see all projects and initiatives" on the bottom right of the FFF box. It shouldn't be there. I used one of Mariana's templates to create the FFF box, and that popped up when it was done.
