### ISSUE TITLE
open links in external tab on the Resources and News page

### ISSUE THREAD

**Issue by fibasile** [fabfoundation/fabfoundation#6]
make the links that are within the news pieces open new tabs

**Comment by fibasile** [comment]
The links in news pieces are currently opening a new tab. Is this ok?

**Comment by rebeccaottinger** [comment]
Currently, if I go to news/press releases and click on the "SCOPESDF website is live" piece, that opens a new tab. Within the piece, clicking on scopesdf.org leads to the external page but not a new tab. Would love it to be the opposite. For example, if I click on the "SCOPESDF website is live" icon, that should not open a new tab, but the external scopesdf.org should. Is that clear?

**Comment by fibasile** [comment]
@rebeccaottinger the links for each news stay now in the same window. To have the news content open links in external pages, you should do them in html:

```
<a href="https://www.fabacademy.org" target="_blank">www.fabacademy.org</a>
```

the key is the target="_blank" attribute.

I edited 2019-02-17-december-newsletter.md post as an example to test

**Comment by rebeccaottinger** [comment]
@fibasile Gotcha! I can do that for the other links...

Can you fix the format of the news pieces in general so that clicking on a news piece does NOT open a new window? So for example, clicking on "December Newsletter" will not lead to a new tab but just stay in the current one?

**Comment by fibasile** [comment]
Yes that's already fixed site-wide

**Comment by rebeccaottinger** [comment]
Ok thank you!
